# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default"
search: false

# Site Settings
title: Aakash Suresh
description: Personal website of Aakash Suresh - UC Berkeley Student and Machine Learning Researcher
url: https://asuresh0524.github.io
baseurl: ""
repository: ASuresh0524/Website

# Site Author
author:
  name: "Aakash Suresh"
  avatar: "profile.jpg"
  bio: "Machine Learning Researcher | Data Engineer | UC Berkeley Student"
  location: "Berkeley, CA"
  employer: "Memorial Sloan Kettering Cancer Center"
  email: aakashsuresh@berkeley.edu
  linkedin: aakash-suresh-cal
  github: ASuresh0524
  phone: "954-516-9922"

# Reading Files
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .github
  - README.md
  - LICENSE

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: single
      author_profile: true
      share: true

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Build settings
markdown: kramdown 