title: Aakash Suresh
description: Personal website of Aakash Suresh - UC Berkeley Student and Machine Learning Researcher
url: https://asuresh0524.github.io
baseurl: "/Website"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md 